### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by Murmandek** [Murmandek/ToDoProject#1]
- [x] add red color for validation messages
- [x] add pagination
- [x] add image compression
- [x] add avatar in Details
- [x] add redirect on an employee details after his create
- [x] change CreateAsync method
- [x] move interfaces to single files
- [x] change style all buttons
